In [1]:
import pandas as pd
import numpy as np

ModuleNotFoundError: No module named 'pandas'

In [9]:
temp = pd.DataFrame({'id': [1], 'chap_id': [7],'problem_id': [1], 'chap_prob': [0.1], 'problem_prob':[0.1]} )

In [69]:
chapIdAndNumProbs = {'7': 28, '8': 35, '9': 41, '13':33, '15':39, '16':28, '20':36, '22':31, '24':49, '25':22, '27':42, '29':14, '30':42}
chapIdAndNumProbs

{'13': 33,
 '15': 39,
 '16': 28,
 '20': 36,
 '22': 31,
 '24': 49,
 '25': 22,
 '27': 42,
 '29': 14,
 '30': 42,
 '7': 28,
 '8': 35,
 '9': 41}

In [70]:
chapIdAndProblemNumber = {chapId : np.arange(1,chapIdAndNumProbs[chapId]+1) for chapId in chapIdAndNumProbs}
chapIdAndProblemNumber

{'13': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]),
 '15': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 36, 37, 38, 39]),
 '16': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28]),
 '20': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 36]),
 '22': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]),
 '24': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
 '25': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22]),
 '27': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 36, 37, 38, 39, 40, 41, 42]),
 '29': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]),
 '30': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 36, 37, 38, 39, 40, 41, 42]),
 '7': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28]),
 '8': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35]),
 '9': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 36, 37, 38, 39, 40, 41])}

In [66]:
# make individual problems in each chapter have equal weights 
chapIdAndProblemProbab = {chapId : np.ones(chapIdAndNumProbs[chapId])*(1/chapIdAndNumProbs[chapId]) for chapId in chapIdAndNumProbs}
chapIdAndProblemProbab

{'13': array([ 0.03030303,  0.03030303,  0.03030303,  0.03030303,  0.03030303,
         0.03030303,  0.03030303,  0.03030303,  0.03030303,  0.03030303,
         0.03030303,  0.03030303,  0.03030303,  0.03030303,  0.03030303,
         0.03030303,  0.03030303,  0.03030303,  0.03030303,  0.03030303,
         0.03030303,  0.03030303,  0.03030303,  0.03030303,  0.03030303,
         0.03030303,  0.03030303,  0.03030303,  0.03030303,  0.03030303,
         0.03030303,  0.03030303,  0.03030303]),
 '15': array([ 0.02564103,  0.02564103,  0.02564103,  0.02564103,  0.02564103,
         0.02564103,  0.02564103,  0.02564103,  0.02564103,  0.02564103,
         0.02564103,  0.02564103,  0.02564103,  0.02564103,  0.02564103,
         0.02564103,  0.02564103,  0.02564103,  0.02564103,  0.02564103,
         0.02564103,  0.02564103,  0.02564103,  0.02564103,  0.02564103,
         0.02564103,  0.02564103,  0.02564103,  0.02564103,  0.02564103,
         0.02564103,  0.02564103,  0.02564103,  0.02564103,  0.02564103,
         0.02564103,  0.02564103,  0.02564103,  0.02564103]),
 '16': array([ 0.03571429,  0.03571429,  0.03571429,  0.03571429,  0.03571429,
         0.03571429,  0.03571429,  0.03571429,  0.03571429,  0.03571429,
         0.03571429,  0.03571429,  0.03571429,  0.03571429,  0.03571429,
         0.03571429,  0.03571429,  0.03571429,  0.03571429,  0.03571429,
         0.03571429,  0.03571429,  0.03571429,  0.03571429,  0.03571429,
         0.03571429,  0.03571429,  0.03571429]),
 '20': array([ 0.02777778,  0.02777778,  0.02777778,  0.02777778,  0.02777778,
         0.02777778,  0.02777778,  0.02777778,  0.02777778,  0.02777778,
         0.02777778,  0.02777778,  0.02777778,  0.02777778,  0.02777778,
         0.02777778,  0.02777778,  0.02777778,  0.02777778,  0.02777778,
         0.02777778,  0.02777778,  0.02777778,  0.02777778,  0.02777778,
         0.02777778,  0.02777778,  0.02777778,  0.02777778,  0.02777778,
         0.02777778,  0.02777778,  0.02777778,  0.02777778,  0.02777778,
         0.02777778]),
 '22': array([ 0.03225806,  0.03225806,  0.03225806,  0.03225806,  0.03225806,
         0.03225806,  0.03225806,  0.03225806,  0.03225806,  0.03225806,
         0.03225806,  0.03225806,  0.03225806,  0.03225806,  0.03225806,
         0.03225806,  0.03225806,  0.03225806,  0.03225806,  0.03225806,
         0.03225806,  0.03225806,  0.03225806,  0.03225806,  0.03225806,
         0.03225806,  0.03225806,  0.03225806,  0.03225806,  0.03225806,
         0.03225806]),
 '24': array([ 0.02040816,  0.02040816,  0.02040816,  0.02040816,  0.02040816,
         0.02040816,  0.02040816,  0.02040816,  0.02040816,  0.02040816,
         0.02040816,  0.02040816,  0.02040816,  0.02040816,  0.02040816,
         0.02040816,  0.02040816,  0.02040816,  0.02040816,  0.02040816,
         0.02040816,  0.02040816,  0.02040816,  0.02040816,  0.02040816,
         0.02040816,  0.02040816,  0.02040816,  0.02040816,  0.02040816,
         0.02040816,  0.02040816,  0.02040816,  0.02040816,  0.02040816,
         0.02040816,  0.02040816,  0.02040816,  0.02040816,  0.02040816,
         0.02040816,  0.02040816,  0.02040816,  0.02040816,  0.02040816,
         0.02040816,  0.02040816,  0.02040816,  0.02040816]),
 '25': array([ 0.04545455,  0.04545455,  0.04545455,  0.04545455,  0.04545455,
         0.04545455,  0.04545455,  0.04545455,  0.04545455,  0.04545455,
         0.04545455,  0.04545455,  0.04545455,  0.04545455,  0.04545455,
         0.04545455,  0.04545455,  0.04545455,  0.04545455,  0.04545455,
         0.04545455,  0.04545455]),
 '27': array([ 0.02380952,  0.02380952,  0.02380952,  0.02380952,  0.02380952,
         0.02380952,  0.02380952,  0.02380952,  0.02380952,  0.02380952,
         0.02380952,  0.02380952,  0.02380952,  0.02380952,  0.02380952,
         0.02380952,  0.02380952,  0.02380952,  0.02380952,  0.02380952,
         0.02380952,  0.02380952,  0.02380952,  0.02380952,  0.02380952,
         0.02380952,  0.02380952,  0.02380952,  0.02380952,  0.02380952,
         0.02380952,  0.02380952,  0.02380952,  0.02380952,  0.02380952,
         0.02380952,  0.02380952,  0.02380952,  0.02380952,  0.02380952,
         0.02380952,  0.02380952]),
 '29': array([ 0.07142857,  0.07142857,  0.07142857,  0.07142857,  0.07142857,
         0.07142857,  0.07142857,  0.07142857,  0.07142857,  0.07142857,
         0.07142857,  0.07142857,  0.07142857,  0.07142857]),
 '30': array([ 0.02380952,  0.02380952,  0.02380952,  0.02380952,  0.02380952,
         0.02380952,  0.02380952,  0.02380952,  0.02380952,  0.02380952,
         0.02380952,  0.02380952,  0.02380952,  0.02380952,  0.02380952,
         0.02380952,  0.02380952,  0.02380952,  0.02380952,  0.02380952,
         0.02380952,  0.02380952,  0.02380952,  0.02380952,  0.02380952,
         0.02380952,  0.02380952,  0.02380952,  0.02380952,  0.02380952,
         0.02380952,  0.02380952,  0.02380952,  0.02380952,  0.02380952,
         0.02380952,  0.02380952,  0.02380952,  0.02380952,  0.02380952,
         0.02380952,  0.02380952]),
 '7': array([ 0.03571429,  0.03571429,  0.03571429,  0.03571429,  0.03571429,
         0.03571429,  0.03571429,  0.03571429,  0.03571429,  0.03571429,
         0.03571429,  0.03571429,  0.03571429,  0.03571429,  0.03571429,
         0.03571429,  0.03571429,  0.03571429,  0.03571429,  0.03571429,
         0.03571429,  0.03571429,  0.03571429,  0.03571429,  0.03571429,
         0.03571429,  0.03571429,  0.03571429]),
 '8': array([ 0.02857143,  0.02857143,  0.02857143,  0.02857143,  0.02857143,
         0.02857143,  0.02857143,  0.02857143,  0.02857143,  0.02857143,
         0.02857143,  0.02857143,  0.02857143,  0.02857143,  0.02857143,
         0.02857143,  0.02857143,  0.02857143,  0.02857143,  0.02857143,
         0.02857143,  0.02857143,  0.02857143,  0.02857143,  0.02857143,
         0.02857143,  0.02857143,  0.02857143,  0.02857143,  0.02857143,
         0.02857143,  0.02857143,  0.02857143,  0.02857143,  0.02857143]),
 '9': array([ 0.02439024,  0.02439024,  0.02439024,  0.02439024,  0.02439024,
         0.02439024,  0.02439024,  0.02439024,  0.02439024,  0.02439024,
         0.02439024,  0.02439024,  0.02439024,  0.02439024,  0.02439024,
         0.02439024,  0.02439024,  0.02439024,  0.02439024,  0.02439024,
         0.02439024,  0.02439024,  0.02439024,  0.02439024,  0.02439024,
         0.02439024,  0.02439024,  0.02439024,  0.02439024,  0.02439024,
         0.02439024,  0.02439024,  0.02439024,  0.02439024,  0.02439024,
         0.02439024,  0.02439024,  0.02439024,  0.02439024,  0.02439024,
         0.02439024])}

In [68]:
# get chapter key list  
chapKeyList = list(chapIdAndProblemNumber.keys())
chapKeyList

['7', '8', '9', '13', '15', '16', '20', '22', '24', '25', '27', '29', '30']

In [71]:
# Make chap probs with equal weighting 
chapProb = {chap : 1/len(chapKeyList) for chap in chapKeyList}
chapProb

{'13': 0.07692307692307693,
 '15': 0.07692307692307693,
 '16': 0.07692307692307693,
 '20': 0.07692307692307693,
 '22': 0.07692307692307693,
 '24': 0.07692307692307693,
 '25': 0.07692307692307693,
 '27': 0.07692307692307693,
 '29': 0.07692307692307693,
 '30': 0.07692307692307693,
 '7': 0.07692307692307693,
 '8': 0.07692307692307693,
 '9': 0.07692307692307693}

In [84]:
newTable = pd.DataFrame.from_dict(chapIdAndProblemNumber, orient='index')
newTable

,0,1,2,3,4,5,6,7,8,9,...,39,40,41,42,43,44,45,46,47,48
7,1,2,3,4,5,6,7,8,9,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1,2,3,4,5,6,7,8,9,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1,2,3,4,5,6,7,8,9,10,...,40.0,41.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,1,2,3,4,5,6,7,8,9,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,1,2,3,4,5,6,7,8,9,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,1,2,3,4,5,6,7,8,9,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,1,2,3,4,5,6,7,8,9,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,1,2,3,4,5,6,7,8,9,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,1,2,3,4,5,6,7,8,9,10,...,40.0,41.0,42.0,43.0,44.0,45.0,46.0,47.0,48.0,49.0
25,1,2,3,4,5,6,7,8,9,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,1,2,3,4,5,6,7,8,9,10,...,40.0,41.0,42.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,1,2,3,4,5,6,7,8,9,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,1,2,3,4,5,6,7,8,9,10,...,40.0,41.0,42.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [92]:
d = df[  for p in chapIdAndProblemNumber]

SyntaxError: invalid syntax (<ipython-input-92-10eb222d18b9>, line 1)

In [94]:
newDataFrame = pd.DataFrame(columns=["id", "chap_id", "problem_id", "chap_prob", "problem_prob" ])
newDataFrame

Empty DataFrame
Columns: [id, chap_id, problem_id, chap_prob, problem_prob]
Index: []

In [122]:
numericId = 1;
for chapter in chapIdAndProblemNumber:
    for problem in chapIdAndProblemNumber[chapter]:
        newDataFrame.append( [numericId, chapter, problem, chapProb[chapter], chapIdAndProblemProbab[chapter][problem-1] ])

/Users/Ismael/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/api.py:77: RuntimeWarning: '<' not supported between instances of 'str' and 'int', sort order is undefined for incomparable objects
  result = result.union(other)

In [121]:
chapIdAndProblemProbab

{'13': array([ 0.03030303,  0.03030303,  0.03030303,  0.03030303,  0.03030303,
         0.03030303,  0.03030303,  0.03030303,  0.03030303,  0.03030303,
         0.03030303,  0.03030303,  0.03030303,  0.03030303,  0.03030303,
         0.03030303,  0.03030303,  0.03030303,  0.03030303,  0.03030303,
         0.03030303,  0.03030303,  0.03030303,  0.03030303,  0.03030303,
         0.03030303,  0.03030303,  0.03030303,  0.03030303,  0.03030303,
         0.03030303,  0.03030303,  0.03030303]),
 '15': array([ 0.02564103,  0.02564103,  0.02564103,  0.02564103,  0.02564103,
         0.02564103,  0.02564103,  0.02564103,  0.02564103,  0.02564103,
         0.02564103,  0.02564103,  0.02564103,  0.02564103,  0.02564103,
         0.02564103,  0.02564103,  0.02564103,  0.02564103,  0.02564103,
         0.02564103,  0.02564103,  0.02564103,  0.02564103,  0.02564103,
         0.02564103,  0.02564103,  0.02564103,  0.02564103,  0.02564103,
         0.02564103,  0.02564103,  0.02564103,  0.02564103,  0.02564103,
         0.02564103,  0.02564103,  0.02564103,  0.02564103]),
 '16': array([ 0.03571429,  0.03571429,  0.03571429,  0.03571429,  0.03571429,
         0.03571429,  0.03571429,  0.03571429,  0.03571429,  0.03571429,
         0.03571429,  0.03571429,  0.03571429,  0.03571429,  0.03571429,
         0.03571429,  0.03571429,  0.03571429,  0.03571429,  0.03571429,
         0.03571429,  0.03571429,  0.03571429,  0.03571429,  0.03571429,
         0.03571429,  0.03571429,  0.03571429]),
 '20': array([ 0.02777778,  0.02777778,  0.02777778,  0.02777778,  0.02777778,
         0.02777778,  0.02777778,  0.02777778,  0.02777778,  0.02777778,
         0.02777778,  0.02777778,  0.02777778,  0.02777778,  0.02777778,
         0.02777778,  0.02777778,  0.02777778,  0.02777778,  0.02777778,
         0.02777778,  0.02777778,  0.02777778,  0.02777778,  0.02777778,
         0.02777778,  0.02777778,  0.02777778,  0.02777778,  0.02777778,
         0.02777778,  0.02777778,  0.02777778,  0.02777778,  0.02777778,
         0.02777778]),
 '22': array([ 0.03225806,  0.03225806,  0.03225806,  0.03225806,  0.03225806,
         0.03225806,  0.03225806,  0.03225806,  0.03225806,  0.03225806,
         0.03225806,  0.03225806,  0.03225806,  0.03225806,  0.03225806,
         0.03225806,  0.03225806,  0.03225806,  0.03225806,  0.03225806,
         0.03225806,  0.03225806,  0.03225806,  0.03225806,  0.03225806,
         0.03225806,  0.03225806,  0.03225806,  0.03225806,  0.03225806,
         0.03225806]),
 '24': array([ 0.02040816,  0.02040816,  0.02040816,  0.02040816,  0.02040816,
         0.02040816,  0.02040816,  0.02040816,  0.02040816,  0.02040816,
         0.02040816,  0.02040816,  0.02040816,  0.02040816,  0.02040816,
         0.02040816,  0.02040816,  0.02040816,  0.02040816,  0.02040816,
         0.02040816,  0.02040816,  0.02040816,  0.02040816,  0.02040816,
         0.02040816,  0.02040816,  0.02040816,  0.02040816,  0.02040816,
         0.02040816,  0.02040816,  0.02040816,  0.02040816,  0.02040816,
         0.02040816,  0.02040816,  0.02040816,  0.02040816,  0.02040816,
         0.02040816,  0.02040816,  0.02040816,  0.02040816,  0.02040816,
         0.02040816,  0.02040816,  0.02040816,  0.02040816]),
 '25': array([ 0.04545455,  0.04545455,  0.04545455,  0.04545455,  0.04545455,
         0.04545455,  0.04545455,  0.04545455,  0.04545455,  0.04545455,
         0.04545455,  0.04545455,  0.04545455,  0.04545455,  0.04545455,
         0.04545455,  0.04545455,  0.04545455,  0.04545455,  0.04545455,
         0.04545455,  0.04545455]),
 '27': array([ 0.02380952,  0.02380952,  0.02380952,  0.02380952,  0.02380952,
         0.02380952,  0.02380952,  0.02380952,  0.02380952,  0.02380952,
         0.02380952,  0.02380952,  0.02380952,  0.02380952,  0.02380952,
         0.02380952,  0.02380952,  0.02380952,  0.02380952,  0.02380952,
         0.02380952,  0.02380952,  0.02380952,  0.02380952,  0.02380952,
         0.02380952,  0.02380952,  0.02380952,  0.02380952,  0.02380952,
         0.02380952,  0.02380952,  0.02380952,  0.02380952,  0.02380952,
         0.02380952,  0.02380952,  0.02380952,  0.02380952,  0.02380952,
         0.02380952,  0.02380952]),
 '29': array([ 0.07142857,  0.07142857,  0.07142857,  0.07142857,  0.07142857,
         0.07142857,  0.07142857,  0.07142857,  0.07142857,  0.07142857,
         0.07142857,  0.07142857,  0.07142857,  0.07142857]),
 '30': array([ 0.02380952,  0.02380952,  0.02380952,  0.02380952,  0.02380952,
         0.02380952,  0.02380952,  0.02380952,  0.02380952,  0.02380952,
         0.02380952,  0.02380952,  0.02380952,  0.02380952,  0.02380952,
         0.02380952,  0.02380952,  0.02380952,  0.02380952,  0.02380952,
         0.02380952,  0.02380952,  0.02380952,  0.02380952,  0.02380952,
         0.02380952,  0.02380952,  0.02380952,  0.02380952,  0.02380952,
         0.02380952,  0.02380952,  0.02380952,  0.02380952,  0.02380952,
         0.02380952,  0.02380952,  0.02380952,  0.02380952,  0.02380952,
         0.02380952,  0.02380952]),
 '7': array([ 0.03571429,  0.03571429,  0.03571429,  0.03571429,  0.03571429,
         0.03571429,  0.03571429,  0.03571429,  0.03571429,  0.03571429,
         0.03571429,  0.03571429,  0.03571429,  0.03571429,  0.03571429,
         0.03571429,  0.03571429,  0.03571429,  0.03571429,  0.03571429,
         0.03571429,  0.03571429,  0.03571429,  0.03571429,  0.03571429,
         0.03571429,  0.03571429,  0.03571429]),
 '8': array([ 0.02857143,  0.02857143,  0.02857143,  0.02857143,  0.02857143,
         0.02857143,  0.02857143,  0.02857143,  0.02857143,  0.02857143,
         0.02857143,  0.02857143,  0.02857143,  0.02857143,  0.02857143,
         0.02857143,  0.02857143,  0.02857143,  0.02857143,  0.02857143,
         0.02857143,  0.02857143,  0.02857143,  0.02857143,  0.02857143,
         0.02857143,  0.02857143,  0.02857143,  0.02857143,  0.02857143,
         0.02857143,  0.02857143,  0.02857143,  0.02857143,  0.02857143]),
 '9': array([ 0.02439024,  0.02439024,  0.02439024,  0.02439024,  0.02439024,
         0.02439024,  0.02439024,  0.02439024,  0.02439024,  0.02439024,
         0.02439024,  0.02439024,  0.02439024,  0.02439024,  0.02439024,
         0.02439024,  0.02439024,  0.02439024,  0.02439024,  0.02439024,
         0.02439024,  0.02439024,  0.02439024,  0.02439024,  0.02439024,
         0.02439024,  0.02439024,  0.02439024,  0.02439024,  0.02439024,
         0.02439024,  0.02439024,  0.02439024,  0.02439024,  0.02439024,
         0.02439024,  0.02439024,  0.02439024,  0.02439024,  0.02439024,
         0.02439024])}

In [107]:
newDataFrame

Empty DataFrame
Columns: [id, chap_id, problem_id, chap_prob, problem_prob]
Index: []